trigger:
  # start a new build for every push
  batch: False
  branches:
    include:
      - develop

jobs:
- job: Linux_Python_36_32bit
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
           docker pull i386/ubuntu:bionic
           docker run -v $(pwd):/mdanalysis i386/ubuntu:bionic /bin/bash -c "cd mdanalysis && \
           apt-get -y update && \
           apt-get -y install python3 python3-pip libfreetype6-dev && \
           python3 -m pip install --user --upgrade pip setuptools && \
           python3 -m pip install --user --upgrade pytest pytest-xdist && \
           python3 -m pip install --user --upgrade cython numpy scipy hypothesis && \
           cd /mdanalysis/package && \
           python3 setup.py install --user && \
           cd .. && \
           /root/.local/bin/pytest --disable-pytest-warnings --durations=50 testsuite/MDAnalysisTests"
    displayName: 'Run 32-bit Ubuntu Docker Build / Tests'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Publish test results for Python 3.6-32 bit Linux'
